add file
krishnakTechnocretids/JAVATechnoCreditsG1 pull request #111
Opened 2019-01-23 18:08 UTC by sakettechnocredit

2019-01-23 18:20 UTC, mkanani13 commented on JavaAssignments/src/saket/swapwiththirdvaiable.java
> +    b=c;
Alignment issue.

2019-01-23 18:22 UTC, mkanani13 requested changes

2019-01-23 18:22 UTC, mkanani13 commented on JavaAssignments/src/saket/swapwiththirdvaiable.java
> +	int a=10;
Why you need instance variable. as you are using these variables in method only. it should be local variable if usage of variable is limited to method. I suggest use parameters of method .. dont use such hardcode value.

2019-01-25 11:28 UTC, sakettechnocredit commented on JavaAssignments/src/saket/swapwiththirdvaiable.java
> +	int a=10;
done

2019-01-25 13:13 UTC, mkanani13 requested changes

2019-01-25 13:13 UTC, mkanani13 commented on JavaAssignments/src/saket/swapwiththirdvaiable.java
> +		return 0;
if you are always returning 0, it doesn't make any sense.
Here you dont need to return anything. you should have return type as void.

2019-01-26 13:45 UTC, mkanani13 approved these changes

2019-01-26 13:45 UTC, mkanani13 commented on JavaAssignments/src/saket/swapwiththirdvaiable.java
> +		A.swap(5, 10);
instead of 5 and 10 you should use args[0] and args[1].

2019-01-26 13:46 UTC, mkanani13 commented
Rest code looks good to me hence I merge your request. Still you want to update code please create new branch and update your code based on given comments.

2019-01-26 13:46 UTC, merged